### PR TITLE
Fix InvalidAuthenticityToken errors using a long-lived CSRF cookie

### LINKED ISSUE #6102: Erreur lors de la réinitialisation du mot de passe
**Décrivez le bug**

Lorsque des usagers cherchent à ré-initialiser leur mot de passe, ils prennent une erreur.
La page d'erreur indique "The change you wanted was rejected".

(On a aussi de ces erreurs au sign-in parfois.)

**Appareil et navigateur utilisés**

- Safari 13.1 on iOS 13.5
- Safari 14 on iOS 14.3/14.4
- Chrome 87/89 on Android
- Samsung Browser 13.2 on Android (Oreo)

**Exemples de messages au support**

Au changement de mot de passe :
* https://secure.helpscout.net/conversation/1475758990/87817/ (Safari mobile, "The change you wanted was rejected")
* https://secure.helpscout.net/conversation/1475277346/87716/ (Safari mobile, "The change you wanted was rejected")
* https://secure.helpscout.net/conversation/1475803339/87825/ 
* https://secure.helpscout.net/conversation/1471652804/87435/ (Safari mobile, "The change you wanted was rejected")
* https://secure.helpscout.net/conversation/1476575652/87882/ ("La procédure Mot de passe oublié ne m'a pas permis de réinitialiser mon mot de passe")

Au sign-in:
* https://secure.helpscout.net/conversation/1490535985/0/?folderId=1653799 ("Le changement que vous vouliez a été rejeté.")

**Détails techniques**

Concrètement, ça a l'air de correspondre à une erreur `ActionController::InvalidAuthenticityToken` dans le `Users::PasswordsController`.

On prend environ 50 de ces erreurs par jour ([logs sur Kibana](http://localhost:9002/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now%2Fw,to:now%2Fw))&_a=(columns:!(path,error_parsed,rails_user_agent),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:db96a0d0-cc97-11e8-a0a9-4f854c3a7a7a,key:status,negate:!t,params:(query:'200'),type:phrase),query:(match_phrase:(status:'200'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:db96a0d0-cc97-11e8-a0a9-4f854c3a7a7a,key:status,negate:!t,params:(query:302),type:phrase),query:(match_phrase:(status:302)))),index:db96a0d0-cc97-11e8-a0a9-4f854c3a7a7a,interval:d,query:(language:kuery,query:'path:*password*'),sort:!()))).

**Pistes d'investigation**

- Un header strippé par un proxy ? ([Rails: request origin does not match request URL](https://github.com/rails/rails/issues/22965))
- Un mauvais SSL ? ([Cloudflare configuration breaks Devise](http://til.obiefernandez.com/posts/875a2a69af-cloudflare-flexible-ssl-mode-breaks-rails-5-csrf))

### PR DESCRIPTION
**Pull request by kemenaran**
This PR fixes `InvalidAuthenticityToken` errors that still creep up in production – especially on sign-in and password reset.

As a refresher, in a Rails app, these errors may be caused by:

1. An actual CSRF attack (uncommon);
2. When an XHR response doesn’t update the `<meta name="csrf-token" …>`;
3. When a browser is closed, re-opened, and a form is displayed from the cache but the session cookie expired;
4. When Safari retries an outdated POST request (e.g. when closing an re-opening the browser after a form error).

## Previously on this topic

In #5042, we fixed 3., by disabling the HTTP cache on HTML pages. This forces the browser to request a fresh page when being re-opened, which causes a new session with a new CSRF token to be generated. This was a recommended workaround in the Rails issue (https://github.com/rails/rails/issues/21948).

However this introduced other subtle errors. For instance, now that the browser is instructed not to cache any HTML page, it will reload a page when clicking the "Back" button after crossing a domain boundary (for instance when redirecting to another site, then hitting "Back"). In that case, Chrome will display an error. But Safari will attempt to display the page by retrying the POST request, without sending any cookies. This will cause a `InvalidAuthenticityToken` error, because the token is missing.

## A new hope

This time, let's attempts instead to fix the root cause: the browser displaying a form page while the session cookie expired.

To achieve that, this PR moves the CSRF token from the session to a standalone long-lived cookie.

When the browser is closed and re-opened, and a stale form page is displayed, the session will still be cleared – but the cookie containing the CSRF token will still be present, and will allow the form POST action to be valid.

This allows to revert back to default cache settings, which fixes the "Back" issues introduced by #5042.

## PR in Rails

This use of a long-lived cookie is already used by Django, and a PR was opened in Rails to use the same method. But this PR is stale since 2017 (https://github.com/rails/rails/pull/41735).

I'll try to update this PR in the following weeks, and see if this behavior could be integrated upstream.

## Final result

Combined to the previous PR which [improved the appearance of the CSRF error page](https://github.com/betagouv/demarches-simplifiees.fr/pull/6310), this should allow no false-positive CSRF errors to occur.

The only exception is for Safari bogus POST-requests, which will still trigger a CSRF-error – but those are now excluded from logging.

Fix #6102, #6062

#### Before : the user sees a confusing error
https://user-images.githubusercontent.com/179923/124897073-3c293780-dfde-11eb-986d-739e40f73393.mov

#### After: the user sees a clearer error, and can retry
https://user-images.githubusercontent.com/179923/124897068-3af80a80-dfde-11eb-8cc6-15c291706fe9.mov

#### Before: the user sees a confusing error
https://user-images.githubusercontent.com/179923/124897283-74c91100-dfde-11eb-80eb-fdbc94f4c0c3.mov

#### After: the previous page is correctly displayed
https://user-images.githubusercontent.com/179923/124897281-7397e400-dfde-11eb-95b6-22641fc3e0fe.mov

### CODE REVIEW

File: app/controllers/application_controller/long_lived_authenticity_token.rb [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+  # See also:
+  # - The Architecture Documentation Record for this choice: docs/adr-csrf-forgery.md
+  # - The Rails issue: https://github.com/rails/rails/issues/21948
+  def real_csrf_token(session) # :doc:
+    # Read the CSRF token from the external long-lived cookie (or generate a new one)
+    #
+    # NB: For retro-compatibility with tokens created before this code was deployed,
+    # also try to read the token from the session.
+
+    csrf_token = cookies.signed[COOKIE_NAME] || session[:_csrf_token] || generate_csrf_token
```
Comment (LeSim) [inline app/controllers/application_controller/long_lived_authenticity_token.rb:18]:
```suggestion
    csrf_token = cookies.signed[COOKIE_NAME] || session[COOKIE_NAME] || generate_csrf_token
```

File: app/controllers/application_controller/long_lived_authenticity_token.rb [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    # Write the (potentially new) token to an external long-lived cookie.
+    #
+    # NB: for forward-compatibility if we ever remove this code and revert back to session cookies,
+    # also write the token to the session.
+    cookies.signed[COOKIE_NAME] = {
+      value: csrf_token,
+      expires: 1.year.from_now,
+      httponly: true
+    }
+    session[:_csrf_token] = csrf_token
```
Comment (LeSim) [inline app/controllers/application_controller/long_lived_authenticity_token.rb:29]:
```suggestion
    session[COOKIE_NAME] = csrf_token
```

**Review by LeSim — APPROVED** [review]
Très impressionnant sur le fond et la forme.

Par contre j'ai un peu la trouille, j'espère qu'on fait pas de trous dans la raquette.

File: app/controllers/application_controller/long_lived_authenticity_token.rb (hunk 1 above)
Comment (kemenaran) [reply app/controllers/application_controller/long_lived_authenticity_token.rb:18]: En fait ça c'est le nom de la clef dans la session telle que définie par Rails, donc on n'a pas la main dessus, il faut le laisser tel quel.

File: app/controllers/application_controller/long_lived_authenticity_token.rb (hunk 2 above)
Comment (kemenaran) [reply app/controllers/application_controller/long_lived_authenticity_token.rb:29]: Pareil ici.

**Review by kemenaran — COMMENTED** [review]
Oui, je suis un peu chatouilleux aussi sur les trous dans la raquette. De fait je suis preneur de ton avis là dessus (si tu te dis que c'est trop, on annule tout.)

Ce qui me donne confiance, c'est que :

- Sur le principe, c'est ce qu'utilisent d'autres frameworks,
- L'implémentation a été testée en prod avant nous (par l'auteur initial),
- L'implémentation est basée sur une PR qui était à peu près approuvée par la core team de rails.

Du coup je me dis qu'on tient la route (et qu'au pire c'est rétro-compatible, donc on peut le désactiver quand on veut sans casser les formulaires des gens). Mais comme tu le sens toi :)
